services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: biblioteca-api-backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run start:dev"

  postgres-db:
    image: postgres:15
    container_name: biblioteca-api-db
    restart: always
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: