services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biblioteca-api-backend-prod
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db 

  postgres-db:
    image: postgres:15-alpine
    container_name: biblioteca-api-db-prod
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres-prod-data: